// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleNodeJSEnv using AI Type  and AI Model 

ROOST_METHOD_HASH=b_fb94df674e
ROOST_METHOD_SIG_HASH=b_15079fdf29


*/

// ********RoostGPT********
const b = require('../js/bootstrap.min');

describe('Bootstrap function b', () => {
  let a, d, e, f;
  
  beforeEach(() => {
    a = jest.fn();
    d = {
      data: jest.fn()
    };
    e = {
      new: jest.fn(),
      b: jest.fn()
    };
    f = jest.fn();
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  test('should call each function with provided function', () => {
    const eachFn = jest.fn();
    b.call({ each: eachFn }, a);
    expect(eachFn).toHaveBeenCalled();
  });

  test('should call data function with "bs.affix"', () => {
    const eachFn = jest.fn((fn) => fn());
    b.call({ each: eachFn }, a);
    expect(d.data).toHaveBeenCalledWith("bs.affix");
  });

  test('should create new instance of c if e is not defined', () => {
    d.data.mockReturnValueOnce(undefined);
    const eachFn = jest.fn((fn) => fn());
    b.call({ each: eachFn }, a);
    expect(e.new).toHaveBeenCalledWith(this, f);
  });

  test('should call b function of e if b is a string', () => {
    const eachFn = jest.fn((fn) => fn());
    b.call({ each: eachFn }, "b");
    expect(e.b).toHaveBeenCalled();
  });
});
