// ********RoostGPT********
/*
Test generated by RoostGPT for test sampleNodeJSEnv using AI Type  and AI Model 

ROOST_METHOD_HASH=f_14aa59bc21
ROOST_METHOD_SIG_HASH=f_daa16fdc9f


*/

// ********RoostGPT********
const { f } = require('../js/bootstrap.min.js');

describe('bootstrap.min.js', () => {

  let g, b, e;

  beforeEach(() => {
    g = {
      removeClass: jest.fn().mockReturnThis(),
      find: jest.fn().mockReturnThis(),
      end: jest.fn().mockReturnThis(),
      attr: jest.fn()
    };

    b = {
      addClass: jest.fn().mockReturnThis(),
      removeClass: jest.fn().mockReturnThis(),
      find: jest.fn().mockReturnThis(),
      parent: jest.fn().mockReturnThis(),
      closest: jest.fn().mockReturnThis(),
      attr: jest.fn(),
      offsetWidth: 0
    };

    e = jest.fn();
  });

  test('f function', () => {
    window.g = g;
    window.b = b;
    window.e = e;
    f();
    expect(g.removeClass).toHaveBeenCalledWith('active');
    expect(g.find).toHaveBeenCalledWith('> .dropdown-menu > .active');
    expect(g.end).toHaveBeenCalled();
    expect(g.attr).toHaveBeenCalledWith('data-toggle', 'tab');
    expect(b.addClass).toHaveBeenCalledWith('active');
    expect(b.find).toHaveBeenCalledWith('[data-toggle="tab"]');
    expect(b.attr).toHaveBeenCalledWith('aria-expanded', true);
    expect(b.parent).toHaveBeenCalledWith('.dropdown-menu');
    expect(b.closest).toHaveBeenCalledWith('li.dropdown');
    expect(e).toHaveBeenCalled();
  });

  test('f function with h true', () => {
    window.g = g;
    window.b = b;
    window.e = e;
    window.h = true;
    f();
    expect(b.addClass).toHaveBeenCalledWith('in');
  });

  test('f function with h false', () => {
    window.g = g;
    window.b = b;
    window.e = e;
    window.h = false;
    f();
    expect(b.removeClass).toHaveBeenCalledWith('fade');
  });
});
